Change 3D Secure to 3D Secure 2
bambora-na/dev.na.bambora.com pull request #156
Opened 2023-05-23 20:50 UTC by jcruzbam

BIC-4450 Change 3D Secure to 3D Secure 2.0 in developer guide

2023-05-24 14:21 UTC, chaganiA requested changes
replied in #nam-rtp-pr channel

2023-05-25 17:02 UTC, chaganiA approved these changes

2023-05-25 17:02 UTC, chaganiA commented on source/docs/guides/3D_secure_2_0.md
> +title: EMV 3D Secure 2.0
Text need to be updated here as well.

2023-05-25 17:02 UTC, chaganiA commented on source/docs/guides/index.md
>              Learn about implementing EMV 3D Secure based payments.
here as well?

2023-05-26 18:51 UTC, jgalvanbam approved these changes
Looks good

2023-05-26 18:52 UTC, merged