ZOO-1273
bambora-na/dev.na.bambora.com pull request #262
Opened 2024-08-23 23:35 UTC by macarreon

Update  browsers supported

2024-08-23 23:38 UTC, jcruzbam approved these changes, later dismissed

2024-08-23 23:48 UTC, jgalvanbam requested changes
pls set this comment instead

Browser support
We support the latest versions of Chrome, Edge, Safari, and Firefox.

2024-08-24 00:08 UTC, jgalvanbam approved these changes
looks good now

2024-08-26 16:59 UTC, merged

2024-08-28 00:25 UTC, Jim-Edwards-Worldline commented
Remove the Android/iOS sections related to the browser, those are just as outdated and part of the scope for removal