FS-54 update swagger and dev docs for merchant report
bambora-na/dev.na.bambora.com pull request #44
Opened 2021-10-19 21:55 UTC by jsmithbam

2021-10-19 22:02 UTC, david-light requested changes

2021-10-19 22:02 UTC, david-light commented on source/docs/guides/merchant_report.md
> +You will be able to view information relating to a merchant or its submerchants including the account status, batch limits, cards eneabled and features.
enable spelt wrong

2021-10-19 22:02 UTC, david-light commented on source/docs/guides/merchant_report.md
> +Requests to the settlement endpoint should include two request headers:
This says settlement

2021-10-19 22:02 UTC, david-light commented on source/docs/guides/merchant_report.md
> +[form](https://dev.na.bambora.com/docs/forms/encode_api_passcode/) which does
should be '...which does the same calculation.' Missing a 'the'

2021-10-19 22:02 UTC, david-light commented on source/docs/guides/merchant_report.md
> +If a submerchant is passed in then only data for that submerchant will be returned
I think submerchant should be sub-merchant to be consistent with other documentation

2021-10-19 22:02 UTC, david-light commented on source/docs/guides/merchant_report.md
> +If you wish to only retrieve information for your own account then the request would be
This should be 
If you wish to retrieve information for all of your sub-merchants then the request would be:

2021-10-19 23:15 UTC, GolnazIrannejad-Bambora approved these changes

2021-10-20 17:54 UTC, david-light approved these changes

2021-10-20 17:55 UTC, merged